#! /bin/sh

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
xinput --disable "SYNA8004:00 06CB:CD8B Touchpad"


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap          1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Emacs state=tiled


$HOME/.config/polybar/launch.sh

